env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:vue/essential'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - vue
rules: {
  semi: warn,
  no-unreachable: error,
  no-alert: error,
  no-console: warn,
  sort-imports: [ "warn", { "ignoreCase": true } ],
  indent: [ "warn", 2, { "SwitchCase": 1 } ],
  no-trailing-spaces: warn,
  no-multi-spaces: warn,
  vue/comment-directive: 0
}